define bgpath = 'images/backgrounds/'

image bg flash =         bgpath + 'flash.png'
image bg blackout =      bgpath + 'blackout.png'
image bg sex_dungeon =   bgpath + 'sex dungeon.png'
image bg madera =        bgpath + 'madera.png'
image bg suffocation =   bgpath + 'suffocation.png'
image bg city =          bgpath + 'city.png'
image bg mall =          bgpath + 'mall.png'
image bg puerkokun =     bgpath + 'puerkokun.png'